pub const IOTest = struct {
    input: []const u8,
    expected_output: []const u8,
};

pub const peek_result = struct {
    type: []const u8,
    value: []const u8,
};

pub const print_result = struct {
    value: []const u8,
};

pub const expected_brainfuck_results = [_]print_result{
    .{ .value = "Output: 0x02" },
    .{ .value = "Output: 0x04" },
    .{ .value = "Output: 0x02" },
    .{ .value = "Output: 0x03" },
    .{ .value = "Output: 0x09" },
};

pub const expected_complex_print_results = [_]print_result{
    .{ .value = "The variable \"number\" is equal to 10" },
    .{ .value = "The variable name \"number\" has 6 letters" },
    .{ .value = "The variable \"number\" is equal to 10 and the name has 6 letters" },
    .{ .value = "end" },
};

pub const calculator_io_tests = [_]IOTest{
    .{ .input = "5 + -2\n", .expected_output = "Output: 3" },
    .{ .input = "5 + -2 * 3\n", .expected_output = "Output: -1" },
    .{ .input = "1000 / 5 + 6 * 2\n", .expected_output = "Output: 212" },
    .{ .input = "2 * (3 + 2) - 6 / 2\n", .expected_output = "Output: 7" },
    .{ .input = "10 / 2 / 5\n", .expected_output = "Output: 1" },
    .{ .input = "20-16\n", .expected_output = "Output: 4" },
};

pub const expected_expressions_results = [_]peek_result{
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "string", .value = "\"end\"" },
};

pub const expected_methods_results = [_]peek_result{
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hello!\"" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hello!\"" },
    .{ .type = "int[]", .value = "[1]" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int", .value = "6" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5]" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"é\"" },
    .{ .type = "string", .value = "\"caf\"" },
    .{ .type = "int[]", .value = "[5, 6]" },
    .{ .type = "int[][]", .value = "[[1, 2], [3, 4]]" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "123.0" },
    .{ .type = "float", .value = "123.4" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "float", .value = "123.0" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x0A" },
    .{ .type = "byte", .value = "0x61" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x0A" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "string", .value = "\"123\"" },
    .{ .type = "string", .value = "\"123.4\"" },
    .{ .type = "string", .value = "\"0\"" },
    .{ .type = "string", .value = "\"0x0A\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "string", .value = "\"both\"" },
    .{ .type = "string", .value = "\"nothing\"" },
    .{ .type = "string", .value = "\"{ species: .DOG, name: \"Spot\" }\"" },
    .{ .type = "string", .value = "\"Spot\"" },
    .{ .type = "string", .value = "\".DOG\"" },
    .{ .type = "string", .value = "\"int\"" },
    .{ .type = "string", .value = "\"byte\"" },
    .{ .type = "string", .value = "\"float\"" },
    .{ .type = "string", .value = "\"string\"" },
    .{ .type = "string", .value = "\"tetra\"" },
    .{ .type = "string", .value = "\"array\"" },
    .{ .type = "string", .value = "\"array\"" },
    .{ .type = "string", .value = "\"Animal\"" },
    .{ .type = "string", .value = "\"string\"" },
    .{ .type = "string", .value = "\"Species\"" },
    .{ .type = "string", .value = "\"Species\"" },
    .{ .type = "string", .value = "\"map\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[1, 2, 3, 99, 4, 5]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[1]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hel!lo\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "-1" },

    .{ .type = "int[]", .value = "[2, 99, 4]" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"ll\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"hello\"" },

    .{ .type = "string", .value = "\"end\"" },
};

pub const expected_bigfile_results = [_]peek_result{
    .{ .type = "int", .value = "81" },
    .{ .type = "string", .value = "\"Overflow\"" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "string", .value = "\"imported function\"" },
    .{ .type = "int", .value = "60" },
    .{ .type = "int", .value = "100" },
    .{ .type = "Color", .value = ".Red" },
    .{ .type = "string", .value = "\"It's blue\"" },
    .{ .type = "string", .value = "\"It's something else\"" },

    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },

    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "8" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "2" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "4" },

    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "11" },
    .{ .type = "int", .value = "11" },
    .{ .type = "int", .value = "21" },
    .{ .type = "int", .value = "12" },
    .{ .type = "int", .value = "11" },

    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "int", .value = "101" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "103" },
    .{ .type = "int", .value = "104" },
    .{ .type = "string", .value = "\"fizzbuzz\"" },
    .{ .type = "int", .value = "106" },
    .{ .type = "int", .value = "107" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "109" },
    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "112" },
    .{ .type = "int", .value = "113" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "int", .value = "1001" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1003" },
    .{ .type = "int", .value = "1004" },
    .{ .type = "string", .value = "\"fizzbuzzer\"" },
    .{ .type = "int", .value = "1006" },
    .{ .type = "int", .value = "1007" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1009" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1012" },
    .{ .type = "int", .value = "1013" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "int", .value = "660" },
    .{ .type = "int", .value = "726" },
    .{ .type = "int", .value = "792" },
    .{ .type = "int", .value = "858" },
    .{ .type = "int", .value = "924" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"/\"" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "string", .value = "\"=\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"-\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"+\"" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"*\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "string", .value = "\"false\"" },
    .{ .type = "int", .value = "0" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"world\"" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"foo\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "string", .value = "\"bar\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "20" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = ">int | float | byte", .value = "10" },
    .{ .type = "int | >float | byte", .value = "12.345" },
    .{ .type = "int | float | >byte", .value = "0x0A" },
    .{ .type = "int", .value = "17" },
    .{ .type = "string", .value = "\"return\"" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "4" },
    .{ .type = "string", .value = "\"M\"" },
    .{ .type = "byte", .value = "0x4D" },
    .{ .type = "int", .value = "1000" },
    .{ .type = "Point", .value = "{ y: 2, x: 5 }" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "2" },
    .{ .type = "int", .value = "8" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "15" },
    .{ .type = "int", .value = "27" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "both" },
    .{ .type = "tetra", .value = "neither" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "int[]", .value = "[111111, 222222, 333333, 444444, 555555]" },
    .{ .type = "int", .value = "444444" },
    .{ .type = "int", .value = "666666" },
    .{ .type = "int", .value = "420000" },
    .{ .type = "int", .value = "420000" },
    .{ .type = "int[]", .value = "[111111, 222222, 333333, 666666, 555555]" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"Fluffy\"" },
    .{ .type = "Species", .value = ".LION" },
    .{ .type = "string", .value = "\"Sam\"" },
    .{ .type = "Species", .value = ".PENGUIN" },
    .{ .type = "string", .value = "\"Nemo\"" },
    .{ .type = "Species", .value = ".WHALE" },
    .{ .type = "int", .value = "779" },
    .{ .type = "int", .value = "782" },
    .{ .type = "string", .value = "\"integer\"" },
    .{ .type = "string", .value = "\"float\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "1.5" },
    .{ .type = "float", .value = "3.5" },
    .{ .type = "float", .value = "4.5" },
    .{ .type = "string", .value = "\"fifteen\"" },
    .{ .type = "string", .value = "\"seventeen\"" },
    .{ .type = "string", .value = "\"one\"" },
    .{ .type = "string", .value = "\"two\"" },
    .{ .type = "string", .value = "\"one\"" },
    .{ .type = "string", .value = "\"two\"" },
    .{ .type = "string", .value = "\"one\"" },
    .{ .type = "string", .value = "\"two\"" },
    .{ .type = "string", .value = "\"red\"" },
    .{ .type = "string", .value = "\"blue\"" },
    .{ .type = "string", .value = "\"Mike\"" },
    .{ .type = "int", .value = "1000" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int[]", .value = "[0, 1, 2, 3]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "int[]", .value = "[10]" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "int", .value = "-58" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"\"" },

    .{ .type = "string", .value = "\"end\"" },
};
