pub const IOTest = struct {
    input: []const u8,
    expected_output: []const u8,
};

pub const peek_result = struct {
    type: []const u8,
    value: []const u8,
};

pub const print_result = struct {
    value: []const u8,
};

pub const expected_brainfuck_results = [_]print_result{
    .{ .value = "Output: 0x02" },
    .{ .value = "Output: 0x04" },
    .{ .value = "Output: 0x02" },
    .{ .value = "Output: 0x03" },
    .{ .value = "Output: 0x09" },
};

pub const expected_array_storage_results = [_]print_result{
    .{ .value = "3 3" },
};

pub const expected_fixed_field_array_results = [_]print_result{
    .{ .value = "8 8 false both" },
    .{ .value = "3 0 9 0" },
};

pub const expected_alias_arrays_results = [_]print_result{
    .{ .value = "1 3 5 7" },
    .{ .value = "20.0" },
    .{ .value = "alpha beta" },
    .{ .value = "k0k1k2" },
};

pub const expected_alias_string_mutation_results = [_]print_result{
    .{ .value = "push hello world" },
    .{ .value = "insert >>hello world" },
    .{ .value = "remove > >hello world" },
    .{ .value = "pop d >hello worl" },
    .{ .value = "pop2 l >hello wor" },
    .{ .value = "clear []" },
    .{ .value = "union int 42" },
    .{ .value = "union str again" },
};

pub const expected_alias_repush_union_results = [_]print_result{
    .{ .value = "3 123" },
    .{ .value = "hello world" },
};

pub const expected_stdlib_methods_results = [_]print_result{
    .{ .value = "push hello! [1, 2, 3, 4] [\"a\", \"b\", \"c\"]" },
    .{ .value = "insert >hello! [0, 1, 2, 3, 4]" },
    .{ .value = "find 6 4 1" },
    .{ .value = "clear [] [] []" },
};

pub const expected_slice_heap_string_results = [_]print_result{
    .{ .value = "asd" },
    .{ .value = "asdf" },
    .{ .value = "asdfgsdf" },
};

pub const expected_union_narrow_results = [_]print_result{
    .{ .value = "single" },
    .{ .value = "a" },
    .{ .value = "b" },
    .{ .value = "c" },
    .{ .value = "strings ints" },
};

pub const expected_union_default_results = [_]print_result{
    .{ .value = "0" },
    .{ .value = "[]" },
    .{ .value = "0.0" },
};

pub const expected_union_stringify_results = [_]print_result{
    .{ .value = "string arm: hello world" },
    .{ .value = "int arm: 42" },
    .{ .value = "enum arm: Error.BAD_ARG" },
    .{ .value = "enum var: .BAD_ARG" },
    .{ .value = "enum lit: .BAD_ARG" },
    .{ .value = "narrowed: 7" },
    .{ .value = "other string tag: still a string" },
    .{ .value = "other int tag: 99" },
    .{ .value = "two enum arms: Error.BAD_ARG" },
    .{ .value = "at string: hello world" },
    .{ .value = "at string enum: Error.BAD_ARG" },
    .{ .value = "loop 0: Error.BAD_ARG" },
    .{ .value = "loop 1: Error.BAD_ARG" },
};

pub const expected_group_test_results = [_]print_result{
    .{ .value = "green" },
    .{ .value = "io" },
    .{ .value = "file:x.txt" },
    .{ .value = "outer-color" },
    .{ .value = "path=x.txt" },
    .{ .value = "color" },
};

pub const expected_union_narrow_read_results = [_]print_result{
    .{ .value = "int=not-fourteen" },
    .{ .value = "str=hi" },
    .{ .value = "else=not-fourteen" },
};

pub const expected_match_struct_results = [_]print_result{
    .{ .value = "type-test=a.txt" },
    .{ .value = "bind=a.txt" },
    .{ .value = "other=second" },
};

pub const expected_match_enum_subject_forms_results = [_]print_result{
    .{ .value = "local=100 param=100" },
    .{ .value = "field=100 index=100 call=10" },
    .{ .value = "field C" },
    .{ .value = "index A" },
    .{ .value = "each A" },
    .{ .value = "each C" },
};

pub const expected_match_union_nothing_arm_results = [_]print_result{
    .{ .value = "int nothing" },
    .{ .value = "user 42" },
    .{ .value = "no user" },
};

pub const expected_as_fallback_diverges_results = [_]print_result{
    .{ .value = "42 kept 7" },
};

pub const expected_group_equals_member_results = [_]print_result{
    .{ .value = "true false false true" },
    .{ .value = "true false true" },
    .{ .value = "branch taken" },
};

pub const expected_match_union_struct_results = [_]print_result{
    .{ .value = "a.txt" },
    .{ .value = "type-test" },
    .{ .value = "int-member" },
    .{ .value = "int" },
    .{ .value = "enum-arm" },
};

pub const expected_match_dead_arm_results = [_]print_result{
    .{ .value = "else" },
    .{ .value = "else-value" },
};

pub const expected_match_union_narrow_results = [_]print_result{
    .{ .value = "path=x.txt" },
    .{ .value = "recolored" },
    .{ .value = "int=not-fourteen" },
    .{ .value = "string=hi" },
};

pub const expected_group_narrow_store_results = [_]print_result{
    .{ .value = "in=y.txt" },
    .{ .value = "after=y.txt" },
    .{ .value = "else-branch" },
};

pub const expected_group_global_copy_results = [_]print_result{
    .{ .value = "assigned=a.txt" },
    .{ .value = "global-store=h.txt" },
    .{ .value = "returned=in.txt" },
};

pub const expected_match_union_global_results = [_]print_result{
    .{ .value = "bare=g.txt" },
    .{ .value = "bound=g.txt" },
    .{ .value = "restored=h.txt" },
};

pub const expected_match_union_multi_results = [_]print_result{
    .{ .value = "number" },
    .{ .value = "bound=g.txt" },
};

pub const expected_nested_struct_return_results = [_]print_result{
    .{ .value = "win" },
    .{ .value = "b1" },
};

pub const expected_runtime_const_if_results = [_]print_result{
    .{ .value = "yes" },
    .{ .value = "checking for args" },
};

pub const expected_global_array_push_results = [_]print_result{
    .{ .value = "4 1 4" },
    .{ .value = "2 7 8" },
    .{ .value = "9 10" },
    .{ .value = "9" },
    .{ .value = "102.0 102.0 102.0" },
    .{ .value = "ok" },
    .{ .value = "2 10 20" },
};

pub const expected_expression_branch_merge_results = [_]print_result{
    .{ .value = "111 222" },
    .{ .value = "10 20 30" },
    .{ .value = "1 2 3 4" },
    .{ .value = "1 2 3 4" },
};

pub const expected_copy_free_return_results = [_]print_result{
    .{ .value = "1 x" },
    .{ .value = "5 6 7 8" },
    .{ .value = "3 4 9" },
    .{ .value = "4 5" },
    .{ .value = "2 y" },
};

pub const expected_fixed_struct_array_results = [_]print_result{
    .{ .value = "1 2 30 4 5 6" },
    .{ .value = "2 31 6" },
    .{ .value = "7.25 1.5 2.5" },
};

pub const expected_fixed_struct_field_array_results = [_]print_result{
    .{ .value = "1 2 3 6" },
    .{ .value = "30" },
    .{ .value = "102 104 106" },
    .{ .value = "[{ y: 102, x: 1 }, { y: 104, x: 30 }, { y: 106, x: 5 }]" },
    .{ .value = "0 0" },
};

pub const expected_union_nothing_match_results = [_]print_result{
    .{ .value = "empty" },
    .{ .value = "piece 7" },
    .{ .value = "direct empty" },
    .{ .value = "direct piece" },
};

pub const expected_union_struct_field_results = [_]print_result{
    .{ .value = "1 1" },
    .{ .value = "7 7" },
    .{ .value = "5 7" },
    .{ .value = "[{ y: 2, x: 1 }, { y: 0, x: 0 }]" },
};

pub const expected_fixed_struct_array_params_results = [_]print_result{
    .{ .value = "5" },
    .{ .value = "1 4" },
    .{ .value = "222 333 111" },
};

pub const expected_float_compare_results = [_]print_result{
    .{ .value = "int_eq_float=true" },
    .{ .value = "float_eq_int=true" },
    .{ .value = "int_lt_float=true" },
    .{ .value = "float_gt_int=true" },
    .{ .value = "int_ne_float=false" },
    .{ .value = "byte_lt_float=true" },
    .{ .value = "byte_eq_float=true" },
    .{ .value = "le_equal=true" },
    .{ .value = "ge_equal=true" },
    .{ .value = "lt_one_ulp=true" },
    .{ .value = "rounding_eq=false" },
    .{ .value = "rounding_ne=true" },
    .{ .value = "zeros_eq=true" },
    .{ .value = "zeros_ne=false" },
    .{ .value = "zeros_lt=false" },
    .{ .value = "inf_gt_max=true" },
    .{ .value = "ninf_lt_min=true" },
    .{ .value = "inf_eq_inf=true" },
    .{ .value = "inf_ne_ninf=true" },
    .{ .value = "inf_ge_inf=true" },
    .{ .value = "nan_eq_nan=false" },
    .{ .value = "nan_ne_nan=true" },
    .{ .value = "nan_ne_num=true" },
    .{ .value = "num_ne_nan=true" },
    .{ .value = "nan_ne_inf=true" },
    .{ .value = "nan_lt=false" },
    .{ .value = "nan_gt=false" },
    .{ .value = "nan_le=false" },
    .{ .value = "nan_ge=false" },
    .{ .value = "nan_self_unequal=true" },
    .{ .value = "num_self_unequal=false" },
    .{ .value = "nan_branch_ne=true" },
    .{ .value = "nan_branch_eq=false" },
    .{ .value = "folded_eq=false" },
    .{ .value = "folded_ne=true" },
};

pub const expected_float_promotion_results = [_]print_result{
    .{ .value = "int_plus_float=5.5 float" },
    .{ .value = "float_times_int=7.5 float" },
    .{ .value = "byte_plus_float=18.5 float" },
    .{ .value = "float_minus_byte=-13.5" },
    .{ .value = "int_pow_float=9.0 float" },
    .{ .value = "float_pow_neg_int=0.5" },
    .{ .value = "int_pow_half=2.0" },
    .{ .value = "int_div_int=1.5 float" },
    .{ .value = "exact_int_div=2.0 float" },
    .{ .value = "byte_div_byte=4.0 float" },
    .{ .value = "neg_int_div=-3.5" },
    .{ .value = "int_div_float=0.25" },
    .{ .value = "big_plus_zero=9007199254740992.0" },
    .{ .value = "compound=42.25" },
    .{ .value = "literal_decl=60.0 float" },
    .{ .value = "literal_arg=7.0" },
    .{ .value = "literal_return=3.0" },
    .{ .value = "literal_field=1.0 2.5" },
    .{ .value = "explicit_widen=3.0" },
    .{ .value = "exact_large=9007199254740992.0 -9007199254740992.0 true" },
    .{ .value = "all_int=[1.0, 2.0, 3.0]" },
    .{ .value = "float_first=[1.5, 2.0, 3.0]" },
    .{ .value = "float_middle=[1.0, 2.5, 3.0]" },
    .{ .value = "float_last=[1.0, 2.0, 3.5]" },
    .{ .value = "inferred_first=[2.5, 1.0] float" },
    .{ .value = "inferred_last=[1.0, 2.5] float" },
    .{ .value = "element_compound=[1.75, 1.875, 9.0]" },
    .{ .value = "sum=6.5" },
};

/// The largest finite f64 and the smallest normal and subnormal ones, in the
/// positional notation every float renders in.
const f64_max_text = "17976931348623157" ++ "0" ** 292 ++ ".0";
const f64_min_normal_text = "0." ++ "0" ** 307 ++ "22250738585072014";
const f64_min_subnormal_text = "0." ++ "0" ** 323 ++ "5";

pub const expected_float_edge_results = [_]print_result{
    .{ .value = "plain=1.0 0.5 -2.25 123456789.125" },
    .{ .value = "exponents=10000000000.0 0.00000015" },
    .{ .value = "rounding=0.30000000000000004" },
    .{ .value = "max=" ++ f64_max_text },
    .{ .value = "max_string=" ++ f64_max_text },
    .{ .value = "max_array=[" ++ f64_max_text ++ "]" },
    .{ .value = "neg_max=-" ++ f64_max_text },
    .{ .value = "min_normal=" ++ f64_min_normal_text },
    .{ .value = "min_subnormal=" ++ f64_min_subnormal_text },
    .{ .value = "min_subnormal_string=" ++ f64_min_subnormal_text },
    .{ .value = "runtime_overflow=inf" },
    .{ .value = "runtime_neg_overflow=-inf" },
    .{ .value = "folded_overflow=inf" },
    .{ .value = "folded_neg_overflow=-inf" },
    .{ .value = "runtime_inf=inf -inf" },
    .{ .value = "folded_inf=inf -inf" },
    .{ .value = "inf_string=inf" },
    .{ .value = "inf_array=[inf, -inf]" },
    .{ .value = "inf_arith=inf -inf" },
    .{ .value = "runtime_underflow=0.0" },
    .{ .value = "folded_underflow=0.0" },
    .{ .value = "neg_zero_literal=-0.0" },
    .{ .value = "neg_zero_runtime=-0.0" },
    .{ .value = "neg_zero_call=-0.0" },
    .{ .value = "neg_zero_product=-0.0" },
    .{ .value = "neg_zero_string=-0.0" },
    .{ .value = "neg_zero_array=[-0.0, 0.0]" },
    .{ .value = "pos_zero_again=0.0" },
    .{ .value = "neg_zero_sign=-inf -inf -inf" },
};

pub const expected_float_convert_results = [_]print_result{
    .{ .value = "int_trunc=2 -2 0 0" },
    .{ .value = "int_exact=1000 9000000000000000 int" },
    .{ .value = "byte_trunc=0x02 0xFF" },
    .{ .value = "float_widen=7.0 16.0 -3.0 float" },
    .{ .value = "float_rounds=9007199254740992.0" },
    .{ .value = "float_parse=3.25 -0.5 1000.0 42.0" },
    .{ .value = "float_parse_inf=inf -inf" },
    .{ .value = "float_parse_nan_unequal=true" },
    .{ .value = "string=0.5 2.0 -1.25 10000000000.0" },
    .{ .value = "round_trip=true true" },
};

pub const expected_floored_arith_results = [_]print_result{
    .{ .value = "c_pow2_mod=1" },
    .{ .value = "c_pow2_idiv=1543" },
    .{ .value = "c_pow2_neg=7" },
    .{ .value = "c_pow2_nidiv=-1544" },
    .{ .value = "c_mod=381" },
    .{ .value = "c_idiv=12" },
    .{ .value = "c_neg=616" },
    .{ .value = "c_nidiv=-13" },
    .{ .value = "exact=0" },
    .{ .value = "exact_idiv=10" },
    .{ .value = "neg_c=0" },
    .{ .value = "neg_c2=-3" },
    .{ .value = "neg_c_idiv=-10" },
    .{ .value = "neg_c2_idiv=10" },
    .{ .value = "minus_one=0" },
    .{ .value = "minus_one_zero=0" },
    .{ .value = "v_mod=5" },
    .{ .value = "v_idiv=-15" },
    .{ .value = "v_mod_neg=-5" },
    .{ .value = "v_idiv_neg=-15" },
    .{ .value = "trunc_idiv=-15" },
    .{ .value = "trunc_imod=5" },
    .{ .value = "cell_idiv=-15" },
    .{ .value = "cell_idiv_neg=-15" },
    .{ .value = "cell_mod=5" },
    .{ .value = "cell_mod_neg=-5" },
};

pub const expected_descriptor_skip_results = [_]print_result{
    .{ .value = "2 3" },
    .{ .value = "{ y: 8, x: 7 }" },
    .{ .value = "1 4" },
};

pub const expected_module_string_interp_results = [_]print_result{
    .{ .value = "frames=1" },
    .{ .value = "frames=2" },
    .{ .value = "frames=3" },
    .{ .value = "limit fps: true" },
    .{ .value = "x=42 sum=43 greet=hello world" },
};

pub const expected_module_method_calls_results = [_]print_result{
    .{ .value = "42 42 7" },
};

pub const expected_module_qualified_collision_results = [_]print_result{
    .{ .value = "105 211" },
};

pub const expected_module_type_identity_results = [_]print_result{
    .{ .value = "a:1 b:two a:1 a:3" },
};

pub const expected_module_alias_owner_results = [_]print_result{
    .{ .value = "1 2" },
};

pub const expected_module_qualified_group_results = [_]print_result{
    .{ .value = "group ok" },
};

pub const expected_module_imported_struct_members_results = [_]print_result{
    .{ .value = "GET GET GET" },
};

pub const expected_inline_zig_test_results = [_]print_result{
    .{ .value = "42" },
    .{ .value = "49" },
    .{ .value = "-42" },
    .{ .value = "5.0" },
    .{ .value = "4.0" },
    .{ .value = "42" },
    .{ .value = "7.5" },
    .{ .value = "4" },
    .{ .value = "hello" },
    .{ .value = "4" },
    .{ .value = "100" },
    .{ .value = "0" },
    .{ .value = "10" },
};

pub const expected_inline_zig_arrays_results = [_]print_result{
    .{ .value = "10" },
    .{ .value = "10" },
    .{ .value = "7.0" },
    .{ .value = "alpha,beta,gamma," },
    .{ .value = "14" },
    .{ .value = "42" },
};

pub const expected_inline_zig_nested_arrays_results = [_]print_result{
    .{ .value = "10" },
    .{ .value = "2 5" },
    .{ .value = "15" },
    .{ .value = "bb ccc" },
    .{ .value = "6" },
    .{ .value = "42" },
};

pub const expected_inline_zig_enums_results = [_]print_result{
    .{ .value = "1 0" },
    .{ .value = ".CAT" },
    .{ .value = "3" },
};

pub const expected_inline_zig_qualified_enum_results = [_]print_result{
    .{ .value = "1" },
    .{ .value = ".OutOfBounds" },
    .{ .value = ".EmptyCollection" },
};

pub const expected_inline_zig_errors_results = [_]print_result{
    .{ .value = "a: ok" },
    .{ .value = "b: .NotFound" },
    .{ .value = "c: .IsDirectory" },
    .{ .value = "d: .NotFound" },
    .{ .value = "e: [payload]" },
    .{ .value = "f: .IsDirectory" },
    .{ .value = "g: 7" },
};

pub const expected_union_nothing_narrow_results = [_]print_result{
    .{ .value = "a: nothing" },
    .{ .value = "b: error" },
    .{ .value = "c: payload" },
    .{ .value = "d: error" },
};

pub const expected_std_file_list_results = [_]print_result{
    .{ .value = "123" },
};

pub const expected_zig_import_test_results = [_]print_result{
    .{ .value = "42" },
    .{ .value = "42" },
    .{ .value = "5.0" },
    .{ .value = "hi from zig" },
};

pub const expected_complex_print_results = [_]print_result{
    .{ .value = "The variable \"number\" is equal to 10" },
    .{ .value = "The variable name \"number\" has 6 letters" },
    .{ .value = "The variable \"number\" is equal to 10 and the name has 6 letters" },
    .{ .value = "[\"1\", \" \", \"+\", \" \", \"2\"]" },
    .{ .value = "end" },
};

pub const calculator_io_tests = [_]IOTest{
    .{ .input = "5 + -2\n", .expected_output = "Output: 3" },
    .{ .input = "5 + -2 * 3\n", .expected_output = "Output: -1" },
    .{ .input = "1000 / 5 + 6 * 2\n", .expected_output = "Output: 212" },
    .{ .input = "2 * (3 + 2) - 6 / 2\n", .expected_output = "Output: 7" },
    .{ .input = "10 / 2 / 5\n", .expected_output = "Output: 1" },
    .{ .input = "20-16\n", .expected_output = "Output: 4" },
};

pub const expected_list_results = [_]peek_result{
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = ">int | nothing", .value = "1" },
    .{ .type = ">int | nothing", .value = "1000000000" },
    .{ .type = ">int | nothing", .value = "1000000000" },
    .{ .type = ">int | nothing", .value = "-100" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = ">int | nothing", .value = "1" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = ">int | nothing", .value = "1000000000" },
    .{ .type = ">int | nothing", .value = "-100" },
};

pub const expected_peek_escapes_results = [_]peek_result{
    .{ .type = "string", .value = "\"Hello, World!\\n\"" },
    .{ .type = "string", .value = "\"a\\tb\"" },
    .{ .type = "string", .value = "\"quote \\\" and slash \\\\\"" },
};

pub const expected_expressions_results = [_]peek_result{
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "25" },
    .{ .type = "int", .value = "30" },
    .{ .type = "float", .value = "11.0" },
    .{ .type = "float", .value = "16.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "int", .value = "64" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "50.5" },
    .{ .type = "int", .value = "-75" },
    .{ .type = "float", .value = "3.3333333333333335" },
    .{ .type = "float", .value = "2.0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "80" },
    .{ .type = "int", .value = "146" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "24" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "512" },
    .{ .type = "float", .value = "7.5" },
    .{ .type = "float", .value = "2.5" },
    .{ .type = "float", .value = "5.0" },
    .{ .type = "int", .value = "16" },
    .{ .type = "float", .value = "4.0" },
    .{ .type = "int", .value = "1026" },
    .{ .type = "int", .value = "1" },
    .{ .type = "float", .value = "1000000.000001" },
    .{ .type = "int", .value = "1073741824" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "float", .value = "0.30000000000000004" },
    .{ .type = "float", .value = "0.3333333333333333" },
    .{ .type = "float", .value = "6.0" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"end\"" },
};

pub const expected_union_enum_return_results = [_]peek_result{
    .{ .type = ">int[] | Error", .value = "[1, 2, 3]" },
    .{ .type = "int[] | >Error", .value = "Error.FailedToShunt" },
};

pub const expected_methods_results = [_]peek_result{
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hello!\"" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hello!\"" },
    .{ .type = "int[]", .value = "[1]" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int", .value = "6" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5]" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"é\"" },
    .{ .type = "string", .value = "\"caf\"" },
    .{ .type = "int[]", .value = "[5, 6]" },
    .{ .type = "int[][]", .value = "[[1, 2], [3, 4]]" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "123" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "123.0" },
    .{ .type = "float", .value = "123.4" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "float", .value = "123.0" },
    .{ .type = "float", .value = "10.0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x0A" },
    .{ .type = "byte", .value = "0x61" },
    .{ .type = "byte", .value = "0x7B" },
    .{ .type = "byte", .value = "0x0A" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "string", .value = "\"123\"" },
    .{ .type = "string", .value = "\"123.4\"" },
    .{ .type = "string", .value = "\"0\"" },
    .{ .type = "string", .value = "\"0x0A\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "string", .value = "\"both\"" },
    .{ .type = "string", .value = "\"nothing\"" },
    .{ .type = "string", .value = "\"{ species: .DOG, name: \\\"Spot\\\" }\"" },
    .{ .type = "string", .value = "\"Spot\"" },
    .{ .type = "string", .value = "\".DOG\"" },
    .{ .type = "string", .value = "\"int\"" },
    .{ .type = "string", .value = "\"byte\"" },
    .{ .type = "string", .value = "\"float\"" },
    .{ .type = "string", .value = "\"string\"" },
    .{ .type = "string", .value = "\"tetra\"" },
    .{ .type = "string", .value = "\"array\"" },
    .{ .type = "string", .value = "\"array\"" },
    .{ .type = "string", .value = "\"Animal\"" },
    .{ .type = "string", .value = "\"string\"" },
    .{ .type = "string", .value = "\"Species\"" },
    .{ .type = "string", .value = "\"Species\"" },
    .{ .type = "string", .value = "\"map\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[1, 2, 3, 99, 4, 5]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[1]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"hel!lo\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"!\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "nothing", .value = "nothing" },
    .{ .type = "string[]", .value = "[]" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "-1" },

    .{ .type = "int[]", .value = "[2, 99, 4]" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "string", .value = "\"ll\"" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "int[]", .value = "[1, 2, 99, 4, 5]" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"hello\"" },

    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"hi\"" },
    .{ .type = "byte[]", .value = "[104, 101, 108, 108, 111]" },
    .{ .type = "byte[]", .value = "[]" },
    .{ .type = "tetra", .value = "true" },

    .{ .type = "string", .value = "\"h\"" },
    .{ .type = "byte", .value = "0x68" },
    .{ .type = "byte", .value = "0x68" },
    .{ .type = "byte", .value = "0x01" },

    .{ .type = "int", .value = "5" },
    .{ .type = "string", .value = "\"c\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "byte[]", .value = "[99, 97, 102, 195, 169]" },
    .{ .type = "int", .value = "5" },

    .{ .type = "string", .value = "\"end\"" },
};

pub const expected_module_private_call_results = [_]peek_result{
    .{ .type = "int", .value = "42" },
};

pub const expected_logic_results = [_]peek_result{
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
};

pub const expected_standard_logic_results = [_]peek_result{
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
};

pub const expected_angel_results = [_]print_result{
    .{ .value = "Bob is alive" },
    .{ .value = "Shakespere is dead" },
    .{ .value = "zombie is alive and dead" },
    .{ .value = "angel neither alive or dead" },
};

pub const expected_import_test_results = [_]peek_result{
    .{ .type = "int", .value = "81" },
    .{ .type = "string", .value = "\"Overflow\"" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "string", .value = "\"imported function\"" },
    .{ .type = "int", .value = "60" },
    .{ .type = "int", .value = "100" },
};

pub const expected_basic_test_results = [_]print_result{
    .{ .value = "x: 42" },
};

pub const expected_alias_test_results = [_]print_result{
    .{ .value = "circle: 20" },
    .{ .value = "shift: 30" },
    .{ .value = "result: nothing" },
};

pub const expected_var_from_const_ref_results = [_]print_result{
    .{ .value = "5 world 9" },
    .{ .value = "10 7 goodbye 3" },
    .{ .value = "42" },
};

pub const expected_bigfile_results = [_]peek_result{
    .{ .type = "int", .value = "81" },
    .{ .type = "string", .value = "\"Overflow\"" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "string", .value = "\"imported function\"" },
    .{ .type = "int", .value = "60" },
    .{ .type = "int", .value = "100" },
    .{ .type = "string", .value = "\"It's blue\"" },
    .{ .type = "string", .value = "\"It's something else\"" },

    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },

    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "8" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "2" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "4" },

    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "11" },
    .{ .type = "int", .value = "11" },
    .{ .type = "int", .value = "21" },
    .{ .type = "int", .value = "12" },
    .{ .type = "int", .value = "11" },

    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "int", .value = "101" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "103" },
    .{ .type = "int", .value = "104" },
    .{ .type = "string", .value = "\"fizzbuzz\"" },
    .{ .type = "int", .value = "106" },
    .{ .type = "int", .value = "107" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "109" },
    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "int", .value = "112" },
    .{ .type = "int", .value = "113" },
    .{ .type = "string", .value = "\"fizz\"" },
    .{ .type = "string", .value = "\"buzz\"" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "int", .value = "1001" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1003" },
    .{ .type = "int", .value = "1004" },
    .{ .type = "string", .value = "\"fizzbuzzer\"" },
    .{ .type = "int", .value = "1006" },
    .{ .type = "int", .value = "1007" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1009" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "int", .value = "1012" },
    .{ .type = "int", .value = "1013" },
    .{ .type = "string", .value = "\"fizzer\"" },
    .{ .type = "string", .value = "\"buzzer\"" },
    .{ .type = "int", .value = "660" },
    .{ .type = "int", .value = "726" },
    .{ .type = "int", .value = "792" },
    .{ .type = "int", .value = "858" },
    .{ .type = "int", .value = "924" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"/\"" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "string", .value = "\"=\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"-\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"+\"" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"*\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "string", .value = "\"false\"" },
    .{ .type = "int", .value = "0" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "int", .value = "1" },
    .{ .type = "string", .value = "\"world\"" },
    .{ .type = "int", .value = "2" },
    .{ .type = "string", .value = "\"foo\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "string", .value = "\"bar\"" },
    .{ .type = "string", .value = "\"true\"" },
    .{ .type = "int", .value = "10" },
    .{ .type = "int", .value = "20" },
    .{ .type = "int", .value = "10" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "int", .value = "50" },
    .{ .type = ">int | byte | float", .value = "10" },
    .{ .type = "int | byte | >float", .value = "12.345" },
    .{ .type = "int | >byte | float", .value = "0x0A" },
    .{ .type = "int", .value = "17" },
    .{ .type = ">int | MyErrorSet", .value = "10" },
    .{ .type = "int | >MyErrorSet", .value = "MyErrorSet.Failed" },
    .{ .type = "int", .value = "10" },
    .{ .type = "MyErrorSet", .value = ".Failed" },

    .{ .type = "string", .value = "\"return\"" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "50" },
    .{ .type = "int", .value = "100" },
    .{ .type = "string", .value = "\"neg\"" },
    .{ .type = "string", .value = "\"zero\"" },
    .{ .type = "string", .value = "\"pos\"" },
    .{ .type = "string", .value = "\"R\"" },
    .{ .type = "string", .value = "\"G\"" },
    .{ .type = "string", .value = "\"B\"" },
    .{ .type = ">int | nothing", .value = "42" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = ">int | string", .value = "30" },
    .{ .type = "int | >string", .value = "\"non_negative_only\"" },
    .{ .type = "string", .value = "\"int_arm\"" },
    .{ .type = "string", .value = "\"float_arm\"" },
    .{ .type = "float", .value = "1.0" },
    .{ .type = "byte", .value = "0xAB" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "byte", .value = "0x01" },
    .{ .type = ">int | nothing", .value = "3" },
    .{ .type = "int | >nothing", .value = "nothing" },
    .{ .type = "int", .value = "26" },
    .{ .type = "int", .value = "4" },
    .{ .type = "string", .value = "\"M\"" },
    .{ .type = "byte", .value = "0x4D" },
    .{ .type = "int", .value = "1000" },
    .{ .type = "Point", .value = "{ y: 2, x: 5 }" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "2" },
    .{ .type = "int", .value = "8" },
    .{ .type = "int", .value = "-1" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "15" },
    .{ .type = "int", .value = "27" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "both" },
    .{ .type = "tetra", .value = "neither" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "int[]", .value = "[111111, 222222, 333333, 444444, 555555]" },
    .{ .type = "int", .value = "444444" },
    .{ .type = "int", .value = "666666" },
    .{ .type = "int", .value = "420000" },
    .{ .type = "int", .value = "420000" },
    .{ .type = "int[]", .value = "[111111, 222222, 333333, 666666, 555555]" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "string", .value = "\"\"" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "4" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int[][]", .value = "[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "2" },
    .{ .type = "int[][]", .value = "[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int[]", .value = "[0, 0, 0, 0, 0]" },

    .{ .type = "string[]", .value = "[]" },
    .{ .type = "string[][]", .value = "[]" },
    .{ .type = "string[]", .value = "[\"hello\"]" },
    .{ .type = "string[]", .value = "[\"hello\"]" },
    .{ .type = "string[][]", .value = "[[\"hello\"]]" },
    .{ .type = "string[][]", .value = "[[\"hello\"], [\"world\"]]" },
    .{ .type = "string[]", .value = "[\"hello\"]" },
    .{ .type = "string[]", .value = "[\"world\"]" },
    .{ .type = "string[]", .value = "[\"hello\"]" },
    .{ .type = "string[]", .value = "[\"world\"]" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string[][]", .value = "[[]]" },
    .{ .type = "string[][]", .value = "[[\"hello\", \"world\"], [\"goodbye\", \"sun\"]]" },
    .{ .type = "string[][]", .value = "[]" },
    .{ .type = "string[][]", .value = "[[]]" },
    .{ .type = "string", .value = "\"Fluffy\"" },
    .{ .type = "Species", .value = ".LION" },
    .{ .type = "string", .value = "\"Sam\"" },
    .{ .type = "Species", .value = ".PENGUIN" },
    .{ .type = "string", .value = "\"Nemo\"" },
    .{ .type = "Species", .value = ".WHALE" },
    .{ .type = "Animal", .value = "{ name: \"Larry\", animal_type: .FROG }" },
    .{ .type = "string", .value = "\"Larry\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "779" },
    .{ .type = "int", .value = "782" },
    .{ .type = "string", .value = "\"integer\"" },
    .{ .type = "string", .value = "\"float\"" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "3" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = ">float | nothing", .value = "1.5" },
    .{ .type = ">float | nothing", .value = "3.5" },
    .{ .type = ">float | nothing", .value = "4.5" },
    .{ .type = "float | >nothing", .value = "nothing" },
    .{ .type = ">string | nothing", .value = "\"Bob\"" },
    .{ .type = ">string | nothing", .value = "\"Sam\"" },
    .{ .type = "string | >nothing", .value = "nothing" },
    .{ .type = "string", .value = "\"Bob\"" },
    .{ .type = "string", .value = "\"Sam\"" },
    .{ .type = "string", .value = "\"not found\"" },
    .{ .type = ">string | nothing", .value = "\"one\"" },
    .{ .type = ">string | nothing", .value = "\"two\"" },
    .{ .type = ">string | nothing", .value = "\"one\"" },
    .{ .type = ">string | nothing", .value = "\"two\"" },
    .{ .type = ">string | nothing", .value = "\"one\"" },
    .{ .type = ">string | nothing", .value = "\"two\"" },
    .{ .type = ">string | nothing", .value = "\"red\"" },
    .{ .type = ">string | nothing", .value = "\"blue\"" },
    .{ .type = "Employee", .value = "{ salary: 1000, person: { age: 26, name: \"Mike\" } }" },
    .{ .type = "Employee", .value = "{ salary: 0, person: { age: 0, name: \"Unknown\" } }" },
    .{ .type = "string", .value = "\"world\"" },
    .{ .type = "string", .value = "\"default\"" },
    .{ .type = "int[]", .value = "[1, 2, 3, 4, 5, 6]" },
    .{ .type = "int[]", .value = "[0, 1, 2, 3]" },
    .{ .type = "int[]", .value = "[]" },
    .{ .type = "int[]", .value = "[10]" },
    .{ .type = "int", .value = "5" },
    .{ .type = "int", .value = "6" },
    .{ .type = "int", .value = "7" },
    .{ .type = "int", .value = "8" },
    .{ .type = "int", .value = "9" },
    .{ .type = "int", .value = "10" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "tetra", .value = "true" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "int", .value = "-58" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "string", .value = "\"I am alive\"" },
    .{ .type = "string", .value = "\"I am dead\"" },
    .{ .type = "int", .value = "0" },
    .{ .type = "float", .value = "0.0" },
    .{ .type = "byte", .value = "0x00" },
    .{ .type = "tetra", .value = "false" },
    .{ .type = "string", .value = "\"\"" },

    .{ .type = "int", .value = "1111" },
    .{ .type = "int", .value = "0" },
    .{ .type = "int", .value = "1110" },
    .{ .type = "int", .value = "33" },
    .{ .type = "int", .value = "113" },
    .{ .type = "int", .value = "13" },
    .{ .type = "string", .value = "\"hello\"" },
    .{ .type = "string", .value = "\"hello\"" },

    .{ .type = "string", .value = "\"end\"" },
};
