site_name: Doxa Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mirror-shades/doxa
  license:
    text: Copyright 2024 Mirror Shades
    url: https://www.gnu.org/licenses/gpl-2.0.en.html

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

plugins:
  - search

nav:
  - Home: index.md
  - Syntax: syntax.md
  - Tetras: tetras.md
  - Alias: alias.md
  - Inline: inline.md
  - Maps: maps.md
  - Structs: struct.md
  - Unions: unions.md
  - Control: control.md
  - Loops: loops.md
  - Methods: methods.md
