///! Centralised registry of built-in functions.
///!
///! Every function that is implemented in the VM/runtime (as opposed to
///! user-defined Doxa code) should be listed here.  The registry is used by:
///!
///!   * **codegen** (`soxa_generator.inferCallReturnType`) – to look up the
///!     HIR return type of a built-in call without hardcoding names.
///!   * **VM dispatch** (`functions.execBuiltinFunction`) – to validate that a
///!     call tagged `.BuiltinFunction` is actually a known built-in.
///!
///! User-defined functions (e.g. `safeAdd`, `foo`, `fizzbuzz`, …) do **not**
///! belong here.  Their return types come from `function_signatures` in the
///! HIRGenerator / TypeSystem.

const std = @import("std");
const HIRType = @import("../codegen/hir/soxa_types.zig").HIRType;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

pub const BuiltinInfo = struct {
    name: []const u8,
    return_type: HIRType,
    /// Expected argument count.  `null` means variadic / context-dependent.
    param_count: ?u32,
};

// ---------------------------------------------------------------------------
// Static table
// ---------------------------------------------------------------------------

pub const BUILTINS = [_]BuiltinInfo{
    // ── Collection operations ───────────────────────────────────────────
    .{ .name = "length", .return_type = .Int, .param_count = 1 },
    .{ .name = "push", .return_type = .Nothing, .param_count = 2 },
    .{ .name = "pop", .return_type = .Unknown, .param_count = 1 }, // element type varies
    .{ .name = "insert", .return_type = .Nothing, .param_count = 3 },
    // NOTE: `remove` is intentionally omitted – codegen treats it as a
    // special-case error (InvalidAliasType) rather than a normal return type.
    .{ .name = "clear", .return_type = .Nothing, .param_count = 1 },
    .{ .name = "find", .return_type = .Int, .param_count = 2 },
    .{ .name = "slice", .return_type = .Unknown, .param_count = 3 },

    // ── I/O ─────────────────────────────────────────────────────────────
    .{ .name = "print", .return_type = .Nothing, .param_count = null },
    .{ .name = "println", .return_type = .Nothing, .param_count = null },
    .{ .name = "input", .return_type = .String, .param_count = 0 },
    .{ .name = "read", .return_type = .String, .param_count = 1 },

    // ── Type conversions ────────────────────────────────────────────────
    .{ .name = "string", .return_type = .String, .param_count = 1 },
    .{ .name = "int", .return_type = .Int, .param_count = 1 },
    .{ .name = "float", .return_type = .Float, .param_count = 1 },
    .{ .name = "byte", .return_type = .Byte, .param_count = 1 },
    .{ .name = "type", .return_type = .String, .param_count = 1 },

    // ── Math ────────────────────────────────────────────────────────────
    .{ .name = "power", .return_type = .Float, .param_count = 2 },
    .{ .name = "powi", .return_type = .Int, .param_count = 2 },
    .{ .name = "random", .return_type = .Float, .param_count = 0 },
    .{ .name = "dice_roll", .return_type = .Int, .param_count = 0 },

    // ── System / timing ─────────────────────────────────────────────────
    .{ .name = "time", .return_type = .Int, .param_count = 0 },
    .{ .name = "tick", .return_type = .Int, .param_count = 0 },
    .{ .name = "os", .return_type = .String, .param_count = 0 },
    .{ .name = "arch", .return_type = .String, .param_count = 0 },
    .{ .name = "abi", .return_type = .String, .param_count = 0 },
    .{ .name = "sleep", .return_type = .Nothing, .param_count = 1 },
    .{ .name = "exit", .return_type = .Nothing, .param_count = 1 },

    // ── Control / diagnostics ───────────────────────────────────────────
    .{ .name = "assert", .return_type = .Nothing, .param_count = null },
    .{ .name = "panic", .return_type = .Nothing, .param_count = 1 },
    .{ .name = "build", .return_type = .Int, .param_count = 6 },

    // ── Quantifier helpers (generated by compiler for ∃/∀ syntax) ──────
    .{ .name = "exists_quantifier_gt", .return_type = .Tetra, .param_count = 2 },
    .{ .name = "exists_quantifier_eq", .return_type = .Tetra, .param_count = 2 },
    .{ .name = "forall_quantifier_gt", .return_type = .Tetra, .param_count = 2 },
    .{ .name = "forall_quantifier_eq", .return_type = .Tetra, .param_count = 2 },
};

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/// Look up a built-in function by name.  Returns `null` when the name does
/// not correspond to any known built-in (i.e. it is user-defined).
pub fn get(name: []const u8) ?*const BuiltinInfo {
    inline for (&BUILTINS) |*entry| {
        if (std.mem.eql(u8, entry.name, name)) return entry;
    }
    return null;
}

/// Convenience: returns `true` when `name` is a recognised built-in.
pub fn isBuiltin(name: []const u8) bool {
    return get(name) != null;
}

/// Return the HIR return type for a built-in, or `null` if unknown.
pub fn getReturnType(name: []const u8) ?HIRType {
    if (get(name)) |info| return info.return_type;
    return null;
}
